version: '3.8'

services:
  fuad_ws:
    build: .
    image: fuad_ws:latest
    container_name: fuad_robotics
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/shm:/dev/shm
    stdin_open: true
    tty: true
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /root/fuad_ws/install/setup.bash &&
        ros2 launch integration_pkg all.launch.py
      "
